name: CI

on: pull_request

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      RAILS_ENV: test
    steps:
      - uses: actions/checkout@v1
      - name: Set Ruby version to use
        run: |
          echo "::set-env name=RUBY_VERSION::$(cat .ruby-version)"
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ env.RUBY_VERSION }}
      - name: Install dependencies
        run: |
          sudo apt-get install libpq-dev
          gem install bundler
          bundle install --jobs 4 --retry 3
      - name: Set up the test database
        run: |
          RAILS_ENV=test bundle exec rake db:setup
      - name: Run the tests
        run: |
          bundle exec rake
